

POST http://localhost:3000/todos/
Content-Type : application/json

{
  "id": 9,
  "todo": "Event JSON theme",
  "priority": "LOW",
  "status": "TO DO",
  "category": "HOME",
  "dueDate": "2021-02-22"
}


GET http://localhost:3000/todos/?status=TO%20DO


GET http://localhost:3000/todos/9